### ISSUE TITLE
Minimize to system tray

### ISSUE THREAD

**Issue by esruv** [spddl/LowAudioLatency#1]
Is there anyway to minimize it to the system tray or implement it?

**Comment by spddl** [comment]
no is not included and not planned.
In KirbyOS this is started as a system and is therefore not visible. On the other hand, you can also uncomment the first line and recompile. Then also no Console is shown. https://github.com/spddl/LowAudioLatency/blob/main/src/main.rs#L1

**Comment by spddl** [comment]
there is another version without console in the release section
