### ISSUE TITLE
Version 2.0.0 does not work

### ISSUE THREAD

**Issue by login404** [spddl/LowAudioLatency#2]
The console shows:
thread '<unnamed>' panicked at 'GetDefaultAudioEnpoint Failed: Error { code: HRESULT(0x80070490), message: "找不到元素。" }', src\sound.rs:31:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Version 1.0.1 and original build https://github.com/miniant-git/REAL works fine
Is it related to the absence of input devices?

**Comment by spddl** [comment]
With version 2.0.0, the latency from the output device (headphones/speakers) is reduced and from the input device (microphones). The return value "E_NOTFOUND" means "No device is available" according to the documentation.

Probably there is no input device or it was not defined as default.
Can you test the new version (2.0.1)?

**Comment by login404** [comment]
Version 2.0.1 works fine
Thanks for the quick fix
