### ISSUE TITLE
I can not open .exe

### ISSUE THREAD

**Issue by lostopkk** [spddl/LowAudioLatency#3]
real works normal, but when I run the lowaudiolatency .exe it doesn't open anything I open it I see the cmd in milliseconds and then it disappears

**Comment by spddl** [comment]
Hello,

what do you see if you open a cmd before and start the program with it?

For me it looks like this:

```
Friendly Name...........Microphone (AT2020USB-X)
Channels................1
Bits per sample.........32 Bit
Samples per sec.........48 kHz
Average.................192000 bytes/s
Buffer size (default)...480 samples (about 10 milliseconds)
Buffer size (min).......480 samples (about 10 milliseconds)
Buffer size (max).......480 samples (about 10 milliseconds)
no change necessary, exit

Friendly Name...........Lautsprecher (DX3 Pro+)
Channels................2
Bits per sample.........32 Bit
Samples per sec.........48 kHz
Average.................384000 bytes/s
Buffer size (default)...480 samples (about 10 milliseconds)
Buffer size (min).......336 samples (about 7 milliseconds)
Buffer size (max).......480 samples (about 10 milliseconds)
```
Important is the "no change necessary, exit".
If for all output and input devices the "Buffer size (min)" is the same with "Buffer size (default)" nothing can be reduced and the program terminates itself. REAL does not close itself even if it does not make any adjustments. 

For me LowAudioLatency in this configuration is only useful for the output device.

Background is that not every sound driver supports this function and if this feature does not exist it closes itself because it is not used. If you use manufacturer drivers it is worth trying to use the Microsoft default drivers.

**Comment by lostopkk** [comment]
> Hello,
> 
> what do you see if you open a cmd before and start the program with it?
> 
> For me it looks like this:
> 
> ```
> Friendly Name...........Microphone (AT2020USB-X)
> Channels................1
> Bits per sample.........32 Bit
> Samples per sec.........48 kHz
> Average.................192000 bytes/s
> Buffer size (default)...480 samples (about 10 milliseconds)
> Buffer size (min).......480 samples (about 10 milliseconds)
> Buffer size (max).......480 samples (about 10 milliseconds)
> no change necessary, exit
> 
> Friendly Name...........Lautsprecher (DX3 Pro+)
> Channels................2
> Bits per sample.........32 Bit
> Samples per sec.........48 kHz
> Average.................384000 bytes/s
> Buffer size (default)...480 samples (about 10 milliseconds)
> Buffer size (min).......336 samples (about 7 milliseconds)
> Buffer size (max).......480 samples (about 10 milliseconds)
> ```
> 
> Important is the "no change necessary, exit". If for all output and input devices the "Buffer size (min)" is the same with "Buffer size (default)" nothing can be reduced and the program terminates itself. REAL does not close itself even if it does not make any adjustments.
> 
> For me LowAudioLatency in this configuration is only useful for the output device.
> 
> Background is that not every sound driver supports this function and if this feature does not exist it closes itself because it is not used. If you use manufacturer drivers it is worth trying to use the Microsoft default drivers.


https://user-images.githubusercontent.com/50776714/234886542-0636610f-418a-4baf-b51b-ccd40ae4e20a.mp4

the program just not opening, look at the video

**Comment by lostopkk** [comment]
> Too bad you don't read what I write. Can you open a cmd console in the folder and run the exe with it?


Now I understand, sorry I can't read English well.
