### ISSUE TITLE
Getting "GetDefaultAudioEndpoint Failed: Error { code: HRESULT(0x80070490), message: "Element not found." }"

### ISSUE THREAD

**Issue by SwiftyPop** [spddl/LowAudioLatency#5]
I able to use the old [REAL](https://github.com/miniant-git/REAL/releases) and that's working just fine but using this, I got this error. What could be the problem?:
![image](https://github.com/spddl/LowAudioLatency/assets/90952326/022fadbc-6f09-4df4-8e76-e2b1ba73c0b4)

**Comment by spddl** [comment]
Check your microphone in windows and try to set it as default

**Comment by SwiftyPop** [comment]
![image](https://github.com/spddl/LowAudioLatency/assets/90952326/228560ae-0e3e-44af-b3de-f0dec0b407ca)
@spddl That seem to be fixed, thanks. All good for me?

**Comment by spddl** [comment]
problem solved :+1:
